<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
	<TargetFrameworks>net10.0</TargetFrameworks>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<OutputPath>bin\</OutputPath>
	<PackageId>A2Z.Episerver.Labs.LanguageManager.GoogleTranslate</PackageId>
	<Version>10.0.0</Version>
	<Description>An extension for EPiServer.Labs.LanguageManager facilitating translation through Google Cloud Translation.</Description>
	<Authors>Adnan Zameer</Authors>
	<IsPackable>True</IsPackable>
	<PackageReleaseNotes>https://github.com/adnanzameer/A2Z.Episerver.Labs.LanguageManager.GoogleTranslate/blob/master/CHANGELOG.md</PackageReleaseNotes>
	<PackageProjectUrl>https://github.com/adnanzameer/A2Z.Episerver.Labs.LanguageManager.GoogleTranslate</PackageProjectUrl>
	<RepositoryUrl>https://github.com/adnanzameer/A2Z.Episerver.Labs.LanguageManager.GoogleTranslate</RepositoryUrl>
	<RepositoryType>Git</RepositoryType>
	<PackageTags>Optimizely LanguageManager Google Translate GoogleTranslate Translation GoogleCloudTranslation</PackageTags>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="EPiServer.Labs.LanguageManager" Version="6.0.0" />
	<PackageReference Include="EPiServer.CMS.UI" Version="13.0.1" />
	<PackageReference Include="Google.Cloud.Translation.V2" Version="3.2.0" />
  </ItemGroup>
  <ItemGroup>
	<None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
